CREATE TABLE public.matricula(
  nu_ano_censo integer,
  id_matricula integer NOT NULL,
  co_pessoa_fisica bigint,
  nu_dia integer,
  nu_mes integer,
  nu_ano integer,
  nu_idade_referencia integer,
  nu_idade integer,
  nu_duracao_turma integer,
  nu_dur_ativ_comp_mesma_rede integer,
  nu_dur_ativ_comp_outras_redes integer,
  nu_dur_aee_mesma_rede integer,
  nu_dur_aee_outras_redes integer,
  nu_dias_atividade integer,
  tp_sexo integer,
  tp_cor_raca integer,
  tp_nacionalidade integer,
  co_pais_origem integer,
  co_uf_nasc integer,
  co_municipio_nasc integer,
  co_uf_end integer,
  co_municipio_end integer,
  tp_zona_residencial integer,
  tp_outro_local_aula integer,
  in_transporte_publico integer,
  tp_responsavel_transporte integer,
  in_transp_vans_kombi integer,
  in_transp_micro_onibus integer,
  in_transp_onibus integer,
  in_transp_bicicleta integer,
  in_transp_tr_animal integer,
  in_transp_outro_veiculo integer,
  in_transp_embar_ate5 integer,
  in_transp_embar_5a15 integer,
  in_transp_embar_15a35 integer,
  in_transp_embar_35 integer,
  in_transp_trem_metro integer,
  in_necessidade_especial integer,
  in_cegueira integer,
  in_baixa_visao integer,
  in_surdez integer,
  in_def_auditiva integer,
  in_surdocegueira integer,
  in_def_fisica integer,
  in_def_intelectual integer,
  in_def_multipla integer,
  in_autismo integer,
  in_sindrome_asperger integer,
  in_sindrome_rett integer,
  in_transtorno_di integer,
  in_superdotacao integer,
  in_recurso_ledor integer,
  in_recurso_transcricao integer,
  in_recurso_interprete integer,
  in_recurso_libras integer,
  in_recurso_labial integer,
  in_recurso_braille integer,
  in_recurso_ampliada_16 integer,
  in_recurso_ampliada_20 integer,
  in_recurso_ampliada_24 integer,
  in_recurso_nenhum integer,
  tp_ingresso_federais integer,
  tp_mediacao_didatico_pedago integer,
  in_especial_exclusiva integer,
  in_regular integer,
  in_eja integer,
  in_profissionalizante integer,
  tp_etapa_ensino integer,
  id_turma integer,
  co_curso_educ_profissional integer,
  tp_unificada integer,
  tp_tipo_turma integer,
  co_entidade integer,
  co_regiao integer,
  co_mesorregiao integer,
  co_microrregiao integer,
  co_uf integer,
  co_municipio integer,
  co_distrito integer,
  tp_dependencia integer,
  tp_localizacao integer,
  tp_categoria_escola_privada integer,
  in_conveniada_pp integer,
  tp_convenio_poder_publico integer,
  in_mant_escola_privada_emp integer,
  in_mant_escola_privada_ong integer,
  in_mant_escola_privada_sind integer,
  in_mant_escola_privada_sist_s integer,
  in_mant_escola_privada_s_fins integer,
  tp_regulamentacao integer,
  tp_localizacao_diferenciada integer,
  in_educacao_indigena integer,
  CONSTRAINT matricula_pkey PRIMARY KEY (id_matricula),
  CONSTRAINT matricula_co_entidade_fkey FOREIGN KEY (co_entidade)
      REFERENCES public.escola (co_entidade) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT matricula_id_turma_fkey FOREIGN KEY (id_turma)
      REFERENCES public.turma (id_turma) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.matricula
  OWNER TO postgres;
