CREATE TABLE public.turma(
  nu_ano_censo integer,
  id_turma integer NOT NULL,
  no_turma character varying(80),
  tx_hr_inicial character varying(2),
  tx_mi_inicial character varying(2),
  nu_duracao_turma integer,
  nu_matriculas integer,
  tp_mediacao_didatico_pedago integer,
  in_especial_exclusiva integer,
  in_regular integer,
  in_eja integer,
  in_profissionalizante integer,
  tp_etapa_ensino integer,
  co_curso_educ_profissional integer,
  tp_tipo_turma integer,
  in_mais_educacao integer,
  nu_dias_atividade integer,
  in_dia_semana_domingo integer,
  in_dia_semana_segunda integer,
  in_dia_semana_terca integer,
  in_dia_semana_quarta integer,
  in_dia_semana_quinta integer,
  in_dia_semana_sexta integer,
  in_dia_semana_sabado integer,
  co_tipo_atividade_1 integer,
  co_tipo_atividade_2 integer,
  co_tipo_atividade_3 integer,
  co_tipo_atividade_4 integer,
  co_tipo_atividade_5 integer,
  co_tipo_atividade_6 integer,
  in_braille integer,
  in_recursos_baixa_visao integer,
  in_processos_mentais integer,
  in_orientacao_mobilidade integer,
  in_sinais integer,
  in_comunicacao_alt_aument integer,
  in_enriq_curricular integer,
  in_soroban integer,
  in_informatica_acessivel integer,
  in_port_escrita integer,
  in_autonomia_escolar integer,
  in_disc_quimica integer,
  in_disc_fisica integer,
  in_disc_matematica integer,
  in_disc_biologia integer,
  in_disc_ciencias integer,
  in_disc_lingua_portuguesa integer,
  in_disc_lingua_ingles integer,
  in_disc_lingua_espanhol integer,
  in_disc_lingua_frances integer,
  in_disc_lingua_outra integer,
  in_disc_lingua_indigena integer,
  in_disc_artes integer,
  in_disc_educacao_fisica integer,
  in_disc_historia integer,
  in_disc_geografia integer,
  in_disc_filosofia integer,
  in_disc_ensino_religioso integer,
  in_disc_estudos_sociais integer,
  in_disc_sociologia integer,
  in_disc_est_sociais_sociologia integer,
  in_disc_informatica_computacao integer,
  in_disc_profissionalizante integer,
  in_disc_atendimento_especiais integer,
  in_disc_diver_socio_cultural integer,
  in_disc_libras integer,
  in_disc_pedagogicas integer,
  in_disc_outras integer,
  co_entidade integer,
  co_regiao integer,
  co_mesorregiao integer,
  co_microrregiao integer,
  co_uf integer,
  co_municipio integer,
  co_distrito integer,
  tp_dependencia integer,
  tp_localizacao integer,
  tp_categoria_escola_privada integer,
  in_conveniada_pp integer,
  tp_convenio_poder_publico integer,
  in_mant_escola_privada_emp integer,
  in_mant_escola_privada_ong integer,
  in_mant_escola_privada_sind integer,
  in_mant_escola_privada_sist_s integer,
  in_mant_escola_privada_s_fins integer,
  tp_regulamentacao integer,
  tp_localizacao_diferenciada integer,
  in_educacao_indigena integer,
  CONSTRAINT turma_pkey PRIMARY KEY (id_turma)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.turma
  OWNER TO postgres;
